#' @name get_metrics
#' @title get_metrics
#' @param x sf. building footprint polygon, typically output from [search_3dglobdf()]
#' @param quiet logical. If `TRUE`, suppress cli messages and progress bars.
#' @note
#' `x` must include a unique `id` field.
#' If `x` includes `group_id`, metrics that represent a whole building are
#' computed on temporary grouped features and copied back to the original rows.
#'
#' @references
#' Anna Labetski, Stelios Vitalis, Filip Biljecki, Ken Arroyo Ohori &
#' Jantien Stoter (2023): 3D building metrics for urban morphology.
#' International Journal of Geographical Information Science, 37(1):
#' 36-67. DOI: 10.1080/13658816.2022.2103818
#'
#' Rachid Hamaina, Thomas Leduc, Guillaume Moreau.
#' Towards Urban Fabrics Characterization Based on Buildings Footprints.
#' Jérôme Gensel; Didier Josselin; Danny Vandenbroucke.
#' Bridging the Geographic Information Sciences- International AGILE’2012 Conference,
#' Avignon (France), April, 24-27, 2012, Springer Berlin Heidelberg,
#' pp.327-346, 2012, 978-3-642-29062-6. 10.1007/978-3-642-290633_18. hal-01347299
#'
#' Melchiorri, M., Freire, S., Schiavina, M. et al.
#' The Multi-temporal and Multi-dimensional Global Urban Centre Database to
#' Delineate and Analyse World Cities. Sci Data 11, 82 (2024).
#' https://doi.org/10.1038/s41597-023-02691-1
#'
#' Essential background in Pesaresi, M. et al. (2024) "Advances on the Global Human
#' Settlement Layer by joint assessment of Earth Observation and population survey data",
#' International Journal of Digital Earth, 17(1).
#'
#' @importFrom terra as.points viewshed cellSize ifel terraOptions
#' @importFrom sf st_as_sf st_nearest_feature st_distance st_centroid st_coordinates st_area st_perimeter
#' @importFrom sf st_minimum_rotated_rectangle
#' @importFrom terra merge
#' @importFrom future plan multisession sequential multicore availableCores
#' @importFrom furrr future_map furrr_options
#' @importFrom parallelly supportsMulticore
#' @importFrom utils txtProgressBar setTxtProgressBar


#' @description
#' `get_morphology`: Computes a set of morphological properties and geometric descriptors for each building footprint polygon.
#' These include area, perimeter, surface area, volume, shape compactness, elongation, and accessibility measures.
#' If `x` contains a `group_id` column, features with the same `group_id` are
#' treated as one building for morphology metrics while the returned rows and
#' geometries remain unchanged.
#' @param metrics vector. A list of metrics to be computed. All metrics will be computed by default.
#' @return
#' `get_morphology` returns an `sf` object identical to input \code{x},
#' with additional columns for:
#' \itemize{
#'  \item \code{g_area}: Ground area of footprint
#'  \item \code{pmeter}: Perimeter length of footprint
#'  \item \code{v_surf}: Vertical surface area (walls)
#'  \item \code{t_surf}: Total surface area (walls + roof)
#'  \item \code{vol}: Volume (area * height)
#'  \item \code{obb_vol}: Volume of oriented bounding box
#'  \item \code{pa_ratio}: Perimeter-area ratio
#'  \item \code{rec}: Rectangular compactness
#'  \item \code{fra}: Fractal dimension ratio
#'  \item \code{cbn}: Cuboidness index
#'  \item \code{hem}: Hemisphericality index
#'  \item \code{cnv}: Convexity index
#'  \item \code{me_dist}: Mean edge accessibility distance
#'  \item \code{mp_dist}: Mean pairwise distance within the footprint
#'  \item \code{vol_exch}: Volume exchange ratio
#'  \item \code{elo_x/elo_y/elo_z}: Elongation ratios (x/y/z axis)
#' }
#'
#' @examples
#' library(gloBFPr)
#' data(globfp_example)
#' globfp_example <- sf::st_as_sfc(globfp_example)
#' result <- gloBFPr::get_morphology(globfp_example[c(1:3),])
#'
#' @export
#' @rdname get_metrics
get_morphology <- function(x = NULL,
                           metrics = c('g_area', 'pmeter', 'v_surf', 't_surf',
                                       'vol', 'obb_vol', 'pa_ratio', 'rec',
                                       'rec', 'fra', 'cbn', 'hem', 'cnv',
                                       'me_dist', 'mp_dist', 'vol_exch', 'elo_x',
                                       'elo_y', 'elo_z'),
                           quiet = FALSE) {
  if (inherits(x, 'NULL')) {
    if (!quiet) cli::cli_alert_info("Please input building footprint polygon generated by `search_3dglobdf()`.")
    return(x)
  }
  projected_poly <- x

  old_opt <- getOption("future.globals.maxSize")
  on.exit(options(future.globals.maxSize = old_opt), add = TRUE)
  options(future.globals.maxSize = 3 * 1024^3)

  workers <- max(1, as.numeric(future::availableCores()) - 1)
  # Set future plan depending on OS
  os <- Sys.info()[["sysname"]]
  if (workers == 1) {
    future::plan(future::sequential)
  } else if (os == "Windows" || isFALSE(parallelly::supportsMulticore())) {
    future::plan(future::multisession, workers = workers)
  } else {
    future::plan(future::multicore, workers = workers)
  }
  on.exit(future::plan(future::sequential), add = TRUE)

  start_time <- Sys.time()
  requested_metrics <- unique(metrics)
  analysis_poly <- prepare_morphology_units(projected_poly)
  group_metrics <- "group_id" %in% names(projected_poly)
  property_metrics <- c("g_area", "pmeter", "v_surf", "t_surf", "vol", "obb_vol")
  required_properties <- intersect(property_metrics, requested_metrics)
  if (any(c("pa_ratio", "rec", "cnv", "hem") %in% requested_metrics)) {
    required_properties <- c(required_properties, "g_area")
  }
  if ("pa_ratio" %in% requested_metrics) {
    required_properties <- c(required_properties, "pmeter")
  }
  if (any(c("fra", "cbn", "hem", "vol_exch") %in% requested_metrics)) {
    required_properties <- c(required_properties, "vol")
  }
  if (any(c("fra", "cbn") %in% requested_metrics)) {
    required_properties <- c(required_properties, "t_surf")
  }
  required_properties <- unique(required_properties)

  #--- Properties ---
  if (!quiet) cli::cli_alert_info('Start computing geometric properties ...')
  if ("g_area" %in% required_properties) analysis_poly$g_area <- get_morphology_property(analysis_poly, "g_area")
  if ("pmeter" %in% required_properties) analysis_poly$pmeter <- get_morphology_property(analysis_poly, "pmeter")
  if ("v_surf" %in% required_properties) analysis_poly$v_surf <- get_morphology_property(analysis_poly, "v_surf")
  if ("t_surf" %in% required_properties) analysis_poly$t_surf <- get_morphology_property(analysis_poly, "t_surf")
  if ("vol" %in% required_properties) analysis_poly$vol <- get_morphology_property(analysis_poly, "vol")
  if ("obb_vol" %in% required_properties) analysis_poly$obb_vol <- get_morphology_property(analysis_poly, "obb_vol")

  #--- Indices ---
  if (!quiet) cli::cli_alert_info('Parallel computing for geometric indices ...')
  if ("pa_ratio" %in% metrics) analysis_poly$pa_ratio <- analysis_poly$pmeter / analysis_poly$g_area # Perimeter-Area Ratio
  if ("rec" %in% metrics) analysis_poly$rec <- as.numeric(analysis_poly$g_area / sf::st_area(sf::st_minimum_rotated_rectangle(analysis_poly)))
  if ("fra" %in% metrics) analysis_poly$fra <- 1 - log(analysis_poly$vol + 1e-9) / (1.5 * log(analysis_poly$t_surf + 1e-9))
  if ("cbn" %in% metrics) analysis_poly$cbn <- 6 * (analysis_poly$vol^2)^(1/3) / analysis_poly$t_surf

  # --- Parallel Loop for Shape Metrics ---
  building_list <- lapply(seq_len(nrow(analysis_poly)), function(i) analysis_poly[i, ])
  morpho_results <- furrr::future_map(
    building_list,
    function(poly_) {
      m <- list()
      if ("hem" %in% metrics) m$hem <- cal_hemisphericality(poly_)
      if ("cnv" %in% metrics) m$cnv <- cal_convexity(poly_)
      group_parts <- if (".group_parts" %in% names(poly_)) poly_$.group_parts[[1]] else NULL
      if ("me_dist" %in% metrics) {
        m$me_dist <- if (is.null(group_parts)) cal_accessibility(poly_) else cal_accessibility_group(group_parts)
      }
      if ("mp_dist" %in% metrics) {
        m$mp_dist <- if (is.null(group_parts)) cal_mean_pairwise_distance(poly_) else cal_mean_pairwise_distance_group(group_parts)
      }
      if ("vol_exch" %in% metrics) m$vol_exch <- cal_volume_exchange_ratio(poly_)
      if ("elo_x" %in% metrics | "elo_y" %in% metrics | "elo_z" %in% metrics) {
        m$elo_ratios <- cal_elongation_ratios(poly_)
      }
      return(m)
    },
    .options = furrr::furrr_options(seed = TRUE),
    .progress = !quiet
  )

  # --- Assign results back ---
  get_metric_value <- function(result, name) {
    value <- result[[name]]
    if (is.null(value) || length(value) != 1 || is.na(value)) return(NA_real_)
    as.numeric(value)
  }
  get_elo_value <- function(result, index) {
    value <- result$elo_ratios
    if (is.null(value) || length(value) < index || length(value[[index]]) != 1) return(NA_real_)
    as.numeric(value[[index]])
  }

  if ("hem" %in% metrics) analysis_poly$hem <- vapply(morpho_results, get_metric_value, numeric(1), name = "hem")
  if ("cnv" %in% metrics) analysis_poly$cnv <- vapply(morpho_results, get_metric_value, numeric(1), name = "cnv")
  if ("me_dist" %in% metrics) analysis_poly$me_dist <- vapply(morpho_results, get_metric_value, numeric(1), name = "me_dist")
  if ("mp_dist" %in% metrics) analysis_poly$mp_dist <- vapply(morpho_results, get_metric_value, numeric(1), name = "mp_dist")
  if ("vol_exch" %in% metrics) analysis_poly$vol_exch <- vapply(morpho_results, get_metric_value, numeric(1), name = "vol_exch")
  if ("elo_x" %in% metrics) analysis_poly$elo_x <- vapply(morpho_results, get_elo_value, numeric(1), index = 1)
  if ("elo_y" %in% metrics) analysis_poly$elo_y <- vapply(morpho_results, get_elo_value, numeric(1), index = 2)
  if ("elo_z" %in% metrics) analysis_poly$elo_z <- vapply(morpho_results, get_elo_value, numeric(1), index = 3)

  metric_cols <- intersect(
    requested_metrics,
    names(analysis_poly)
  )
  if (group_metrics) {
    match_idx <- match(projected_poly$group_id, analysis_poly$group_id)
    for (col in metric_cols) {
      projected_poly[[col]] <- analysis_poly[[col]][match_idx]
    }
  } else {
    for (col in metric_cols) {
      projected_poly[[col]] <- analysis_poly[[col]]
    }
  }

  if (!quiet) cli::cli_alert_success('Finished computing morphology metrics')

  end_time <- Sys.time()
  process_time <- as.numeric(difftime(end_time, start_time, units = "secs"))
  if (!quiet) time_taken(process_time)

  return(projected_poly)
}

#' @description
#' `get_pop_density`: Downloads and extracts population density data from the GHSL
#' (Global Human Settlement Layer) dataset for a specified year, and assigns
#' population density values to each input building polygon based on its
#' centroid location.
#'
#' @param year numeric. (only required for `get_pop_density`) Year of the GHSL
#' dataset to use. Must be one of: 1975, 1980, 1985, 1990, 1995, 2000, 2005,
#' 2010, 2015, 2020, 2025, or 2030. Default is 2025.
#' @param distance numeric. (optional, only used by `get_pop_density`) Buffer
#' radius in meters around each building centroid for population aggregation.
#' If `NULL`, population density is extracted from the GHSL cell containing the
#' building centroid. Default is `NULL`.
#'
#' @return
#' `get_pop_density` returns an `sf` object identical to input \code{x},
#' with added columns:
#' \itemize{
#'   \item \code{pop_total}: Estimated total population in the GHSL cell
#'   containing the building centroid, or within the centroid buffer if
#'   `distance` is provided.
#'   \item \code{pop_den}: Estimated population density (people per square
#'   meter) in the GHSL cell containing the building centroid, or within the
#'   centroid buffer if `distance` is provided.
#' }
#'
#' @examples
#' result <- gloBFPr::get_pop_density(# globfp_example[c(1:3),],
#'                                    year = 2025)
#'
#'
#' @export
#' @rdname get_metrics
get_pop_density <- function(x = NULL, year = 2025, distance = NULL, quiet = FALSE) {
  if (inherits(x, 'NULL')) {
    if (!quiet) cli::cli_alert_info("Please input building footprint polygon generated by `search_3dglobdf()`.")
    return(x)
  }
  if (!inherits(distance, "NULL") && (!is.numeric(distance) || length(distance) != 1 || is.na(distance) || distance <= 0)) {
    stop("`distance` must be NULL or a single positive numeric value in meters.", call. = FALSE)
  }

  # Store the original terra progress option and ensure it is reset on exit.
  old_terra_progress <- terra::terraOptions(print = FALSE)$progress
  terra::terraOptions(progress = 0)
  on.exit(terra::terraOptions(progress = old_terra_progress), add = TRUE)

  start_time <- Sys.time()

  input_bbox <- get_bbox(x)
  utm_crs <- get_utm_crs(input_bbox)
  projected_poly <- sf::st_transform(x, utm_crs)
  analysis_poly <- prepare_group_analysis_buildings(projected_poly)

  # Extract values inside the GHSL helper so downloaded raster sources remain
  # available while terra reads them.
  centroids <- suppressWarnings(sf::st_centroid(analysis_poly))
  if (inherits(distance, "NULL")) {
    pop <- get_GHSpop(bbox = input_bbox, year = year, points = centroids, quiet = quiet)
  } else {
    pop_buffers <- sf::st_buffer(centroids, dist = distance)
    pop <- get_GHSpop(
      bbox = get_bbox(pop_buffers),
      year = year,
      polygons = pop_buffers,
      quiet = quiet
    )
  }

  # link pop_density_df back to projected_poly
  analysis_poly$pop_total <- pop$pop_total
  analysis_poly$pop_den <- pop$pop_den
  projected_poly <- copy_group_results(projected_poly, analysis_poly, c("pop_total", "pop_den"))

  if (!quiet) cli::cli_alert_success('Finished linking (GHSL) population density to buildings')
  end_time <- Sys.time()
  process_time <- as.numeric(difftime(end_time, start_time, units = "secs"))
  if (!quiet) time_taken(process_time)

  return(projected_poly)
}

#' @description
#' `get_residential`: Estimate residential and non-residential building based on
#' Global Human Settlement Layer (GHSL) built-up surface data
#' @param threshold numeric. threshould (%) for decide whether a building is
#' residential or not. For example, if `threshold = 70`, a building, located in
#' a cell with more than 70% is residential building footprint area, is classified
#' as residential.
#' @return
#' `get_residential` returns an `sf` object identical to input \code{x},
#' with additional columns :
#' \code{res}: logical. Whether the building is residential or not.
#' \code{res_pct}: numeric. Residential built-up surface percentage in the
#' matched GHSL cell.
#' \code{total_built_vals}, \code{nres_vals}, and \code{res_vals}: numeric.
#' Extracted total, non-residential, and residential built-up surface values
#' from the matched GHSL cell.
#'
#' @examples
#' result <- gloBFPr::get_residential(globfp_example[c(1:3),])
#'
#' @export
#' @rdname get_metrics
get_residential <- function(x = NULL, year = NULL, threshold = 80, quiet = FALSE) {
  if (inherits(x, 'NULL')) {
    if (!quiet) cli::cli_alert_info("Please input building footprint polygon generated by `search_3dglobdf()`.")
    return(NULL)
  }

  if (inherits(year, 'NULL')) {
    if (!quiet) cli::cli_alert_info("Please input year")
    return(NULL)
  }

  terra::terraOptions(progress=0)
  on.exit(terra::terraOptions(progress=3), add = TRUE)

  start_time <- Sys.time()

  bbox <- get_bbox(x)
  utm_crs <- get_utm_crs(bbox)
  projected_poly <- sf::st_transform(x, utm_crs)
  analysis_poly <- prepare_group_analysis_buildings(projected_poly)
  analysis_poly$res <- FALSE
  analysis_poly$g_area <- as.numeric(sf::st_area(analysis_poly$geometry))

  # calculate residential
  ghs <- get_GHSres(bbox = bbox, year = year)
  if (!all(c("total", "nres", "res") %in% names(ghs))) {
    stop("`get_GHSres()` must return total, nres, and res rasters.")
  }

  # use all centroids of projected_poly to extract value from rasters
  centroids <- terra::vect(suppressWarnings(sf::st_centroid(analysis_poly)))
  total_vals <- suppressWarnings(
    terra::extract(ghs$total, centroids, raw = TRUE, ID = FALSE)[, 1]
  )
  nres_vals <- suppressWarnings(
    terra::extract(ghs$nres, centroids, raw = TRUE, ID = FALSE)[, 1]
  )
  res_vals <- suppressWarnings(
    terra::extract(ghs$res, centroids, raw = TRUE, ID = FALSE)[, 1]
  )

  # link building surface area back to projected_poly
  analysis_poly$total_built_vals <- total_vals
  analysis_poly$nres_vals <- nres_vals
  analysis_poly$res_vals <- res_vals
  analysis_poly$res_pct <- ifelse(
    !is.na(total_vals) & total_vals > 0,
    100 * res_vals / total_vals,
    NA_real_
  )

  # classify residential building
  analysis_poly$res <- !is.na(analysis_poly$res_pct) &
    analysis_poly$total_built_vals > 0 &
    analysis_poly$res_pct >= threshold
  projected_poly <- copy_group_results(
    projected_poly,
    analysis_poly,
    c("g_area", "total_built_vals", "nres_vals", "res_vals", "res_pct", "res")
  )

  if (!quiet) cli::cli_alert_success('Finished estimating residential buildings')
  end_time <- Sys.time()
  process_time <- as.numeric(difftime(end_time, start_time, units = "secs"))
  if (!quiet) time_taken(process_time)

  return(projected_poly)
}

#' @description
#' `get_neighbors`: Computes the number of neighboring buildings and centroid
#' distance summaries, based on a fixed-radius buffer and
#' Voronoi-based adjacency.
#'
#' @param radius numeric. (only required for `get_neighbors`, `get_gbvi`, and
#' `get_dng`)
#' A numeric value specifying the buffer radius (in meters) used to define
#' the proximity of a building footprint centroid. Default for `get_neighbors`, and
#' `get_gbvi` and `get_dng` is respectfully 500 and 800.
#'
#' @return
#' `get_neighbors` returns an `sf` object identical to input \code{x},
#' with additional columns for:
#' \itemize{
#'   \item \code{n_count}: Number of adjacent buildings within the radius.
#'   \item \code{m_ndist}: Mean distance from the building centroid
#'   to neighboring building centroids.
#'   \item \code{min_ndist}: Minimum distance to neighboring building centroids.
#'   \item \code{max_ndist}: Maximum distance to neighboring building centroids.
#'   \item \code{sd_ndist}: Standard deviation of those distances.
#' }
#'
#'
#' @examples
#' result <- gloBFPr::get_neighbors(globfp_example[c(1:3),], radius = 100)
#' @importFrom Rcpp evalCpp
#' @export
#' @rdname get_metrics
get_neighbors <- function(x = NULL, radius = 500, quiet = FALSE) {
  if (inherits(x, 'NULL')) {
    if (!quiet) cli::cli_alert_info("Please input building footprint polygon generated by `search_3dglobdf()`.")
    return(x)
  }

  old_opt <- getOption("future.globals.maxSize")
  on.exit(options(future.globals.maxSize = old_opt), add = TRUE)
  options(future.globals.maxSize = 3 * 1024^3)

  workers <- max(1, as.numeric(future::availableCores()) - 1)
  # Set future plan depending on OS
  os <- Sys.info()[["sysname"]]
  if (workers == 1) {
    future::plan(future::sequential)
  } else if (os == "Windows" || isFALSE(parallelly::supportsMulticore())) {
    future::plan(future::multisession, workers = workers)
  } else {
    future::plan(future::multicore, workers = workers)
  }

  start_time <- Sys.time()
  utm_crs <- get_utm_crs(get_bbox(x))
  projected_poly <- sf::st_transform(x, utm_crs)
  analysis_poly <- prepare_group_analysis_buildings(projected_poly)

  # Ensure consistent IDs
  if (!"id" %in% names(analysis_poly)) {
    analysis_poly$id <- seq_len(nrow(analysis_poly))
  }

  # Precompute centroids once
  all_centroids <- suppressWarnings(sf::st_centroid(analysis_poly))

  # Prepare a list of per-building input objects
  if (!quiet) pb <- utils::txtProgressBar(min = 0, max = nrow(analysis_poly), style = 3)
  input_list <- lapply(seq_len(nrow(analysis_poly)), function(i) {
    if (!quiet) utils::setTxtProgressBar(pb, i)
    list(
      poly = analysis_poly[i, ],
      poly_id = analysis_poly$id[i],
      all_polys = analysis_poly,
      all_centroids = all_centroids,
      radius = radius
    )
  })
  if (!quiet) close(pb)

  # Parallel computation
  neighbor_results <- furrr::future_map(
    input_list,
    function(b) {
      poly_ <- b$poly
      poly_id <- b$poly_id
      all_polys <- b$all_polys
      all_centroids <- b$all_centroids
      radius <- b$radius

      # Get centroid and buffer
      this_centroid <- suppressWarnings(sf::st_centroid(poly_))
      buffer_zone <- sf::st_buffer(this_centroid, dist = radius)
      buffer_zone <- sf::st_transform(buffer_zone, sf::st_crs(all_polys))

      # Filter neighbors within buffer
      intersected <- sf::st_intersects(all_polys, buffer_zone, sparse = FALSE)[, 1]
      if (sum(intersected) <= 1) {
        return(list(n = 0, m = NA_real_, min = NA_real_, max = NA_real_, sd = NA_real_))
      }

      filtered_poly <- all_polys[intersected, ]
      filtered_centroids <- all_centroids[intersected, ]
      centroid_union <- sf::st_union(filtered_centroids)
      voronoi_polygons <- sf::st_voronoi(centroid_union) |>
        sf::st_collection_extract("POLYGON")
      voronoi_sf <- sf::st_sf(geometry = sf::st_sfc(voronoi_polygons),
                              crs = sf::st_crs(filtered_poly))
      voronoi_sf$id <- seq_len(nrow(filtered_poly))

      # Index of current building in filtered set
      idx <- which(filtered_poly$id == poly_id)
      if (length(idx) == 0) {
        return(list(n = 0, m = NA_real_, min = NA_real_, max = NA_real_, sd = NA_real_))
      }

      # Find touching polygons
      adjacency <- sf::st_touches(voronoi_sf)
      neighbor_ids <- adjacency[[idx]]
      if (length(neighbor_ids) == 0) {
        return(list(n = 0, m = NA_real_, min = NA_real_, max = NA_real_, sd = NA_real_))
      }

      neighbor_centroids <- filtered_centroids[neighbor_ids, ]
      dists <- sf::st_distance(this_centroid, neighbor_centroids)
      dist_values <- as.numeric(dists)
      mean_dist <- mean(dist_values)
      min_dist <- min(dist_values)
      max_dist <- max(dist_values)
      sd_dist <- if (length(dist_values) > 1) stats::sd(dist_values) else NA_real_

      return(list(n = length(neighbor_ids), m = mean_dist, min = min_dist, max = max_dist, sd = sd_dist))
    },
    .options = furrr::furrr_options(seed = TRUE),
    .progress = !quiet
  )

  # Combine results back into the main data
  analysis_poly$n_count <- vapply(neighbor_results, function(x) x$n, numeric(1))
  analysis_poly$m_ndist <- vapply(neighbor_results, function(x) x$m, numeric(1))
  analysis_poly$min_ndist <- vapply(neighbor_results, function(x) x$min, numeric(1))
  analysis_poly$max_ndist <- vapply(neighbor_results, function(x) x$max, numeric(1))
  analysis_poly$sd_ndist <- vapply(neighbor_results, function(x) x$sd, numeric(1))
  projected_poly <- copy_group_results(
    projected_poly,
    analysis_poly,
    c("n_count", "m_ndist", "min_ndist", "max_ndist", "sd_ndist")
  )

  end_time <- Sys.time()
  process_time <- as.numeric(difftime(end_time, start_time, units = "secs"))
  if (!quiet) time_taken(process_time)

  return(projected_poly)
}


#' @description
#' `get_bgvi`: Calculate the Building Green View Index (BGVI) for each building volume
#' @param datasource_canopy_height character or `NULL`. Canopy height source for
#' building the DSM and canopy green feature layer. Currently supports
#' \code{"metachm"}, \code{"ethCHM"}, or `NULL`. If `NULL`, the DSM is built
#' from buildings and DEM only.
#' @param datasource_greenspace character or `NULL`. Optional 2D greenspace map
#' tile source for the visible-green feature layer. Supports \code{"esri"} and
#' \code{"sentinel2"}. If both canopy height and greenspace sources are supplied,
#' the visible-green layer is the union of height-filtered canopy and 2D
#' greenspace.
#' @param datasource character or `NULL`. Deprecated compatibility argument for
#' older calls to `get_bgvi()`. Use `datasource_canopy_height` and
#' `datasource_greenspace` instead.
#' @param min_tree_height numeric. (only required for `get_bgvi` and `get_dng`)
#' When `datasource_canopy_height` is a canopy height source, minimum height threshold (in
#' meters) to classify vegetation as trees in the CHM. Default is 2.
#' @param zoom numeric. (only required for `get_bgvi` and `get_dng`)
#' Zoom level of map tile when `datasource_greenspace = "esri"` or
#' `datasource_greenspace = "sentinel2"`.
#' The default is `17`. The higher level of zoom will lead to higher resolution
#' of greenspace data for computing BGVI or DNG.
#' @param year numeric. The desired year for Sentinel-2 cloudless mosaic
#' tiles. (This has to be specified when `datasource_greenspace = "sentinel2"`)
#' @param floor logical. (only required for `get_bgvi`)
#' Whether to compute Building Green View Index (BGVI) for each floor level
#' based on estimated number of floors. Default is `FALSE`.
#' @param floor_step integer. (only required for `get_bgvi` when
#' \code{floor = TRUE}) Compute GVI every \code{floor_step} floors. The top
#' estimated floor is always included. Default is \code{1}, meaning every floor.
#' @param short_building_threshold numeric. (only required for `get_bgvi`)
#' Height threshold in meters for deciding whether a building should use only
#' the bottom viewpoint in non-floor mode. Default is 6.
#' @param field_of_view numeric. (only required for directional `get_bgvi`)
#' Angular field of view in degrees for direction-specific GVI. Used only when
#' `directions` is not `NULL`. Default is 45.
#' @param directions character vector or `NULL`. Optional direction names for
#' direction-specific GVI. Valid values are \code{"southwest"},
#' \code{"southeast"}, \code{"northeast"}, \code{"northwest"}, \code{"north"},
#' \code{"east"}, \code{"west"}, and \code{"south"}. If `NULL`,
#' `field_of_view` is ignored and only non-directional GVI columns are returned.
#' @param workers integer. (only required for `get_bgvi`) Number of parallel
#' workers. Defaults to one fewer than available cores, capped at 4. Use
#' \code{workers = 1} to run sequentially and reduce memory pressure.
#' @param key character. (only required for `get_bgvi`)
#' API key of OpenTopography.
#'
#' @details
#' When `floor = TRUE`, `get_bgvi()` estimates the number of floors from
#' building height and computes GVI from selected floor viewpoints. The
#' `floor_step` argument controls how densely floors are sampled. If
#' `floor_step = 1`, GVI is computed for every estimated floor. If
#' `floor_step > 1`, GVI is computed every `floor_step` floors to reduce
#' runtime; for example, `floor_step = 3` samples floors 1, 4, 7, and so on.
#' The top estimated floor is always included, even when it does not fall on
#' the step sequence.
#'
#' If `directions` is provided, `get_bgvi()` also computes direction-specific
#' GVI by applying the requested `field_of_view` around each direction within
#' each computed viewshed. The viewshed itself is computed once per viewpoint,
#' then reused for each direction. Direction-specific columns are named with the
#' direction suffix, such as \code{gvi_bottom_south}, \code{gvi_top_south},
#' \code{mean_gvi_south}, \code{min_gvi_south}, \code{max_gvi_south}, and
#' \code{sd_gvi_south}.
#'
#' @return
#' `get_bgvi` returns an `sf` object identical to input \code{x},
#' with additional columns for:
#' \itemize{
#'   \item \code{mean_gvi}: Mean Building Green View Index value (0 to 1) from selected height(s).
#'   \item \code{bottom_gvi}: Building Green View Index from the bottom
#'   viewpoint, 1.7 m above ground.
#'   \item \code{top_gvi}: Building Green View Index from the top viewpoint.
#'   For short buildings, this is equal to \code{bottom_gvi}.
#'   \item \code{min_gvi}, \code{max_gvi}, \code{sd_gvi}: Minimum, maximum,
#'   and standard deviation of Green View Index (GVI) (if \code{floor = TRUE}).
#'   \item \code{estimated_floors}: Estimated number of floors based on building height
#'   (if \code{floor = TRUE}).
#'}
#'
#' @note
#' To request an OpenTopography API token, please visit:
#' [https://portal.opentopography.org/requestService?service=api](https://portal.opentopography.org/requestService?service=api)
#'
#' USGS 3DEP 1m/10m raster dataset is currently restricted to academic users.
#' Academic users can request access to these data via the OpenTopography portal.
#' Non-academic users can enquire about an enterprise API key by emailing info@opentopography.org.
#' See OpenTopography Terms of Use for more information on appropriate use of the API.
#'
#'
#' @examples
#' \donttest{
#' result <- gloBFPr::get_bgvi(globfp_example[c(1:3),],
#'                             datasource_canopy_height = "metachm",
#'                             datasource_greenspace = "esri",
#'                             key = "YOUR_opentopography_API_KEY")
#' }
#'
#' @references
#' Qi, L., Hu, Y., Bu, R., Xiong, Z., Li, B., Zhang, C., ... & Li, C. (2024).
#' Spatial-temporal patterns and influencing factors of the Building Green View
#' Index: A new approach for quantifying 3D urban greenery visibility.
#' Sustainable Cities and Society, 111, 105518.
#'
#' @export
#' @rdname get_metrics

get_bgvi <- function(x = NULL,
                     datasource_canopy_height = "metachm",
                     datasource_greenspace = NULL,
                     datasource = NULL,
                     min_tree_height = 2,
                     zoom = 17,
                     radius = 800,
                     year = NULL,
                     floor = FALSE,
                     floor_step = 3,
                     short_building_threshold = 6,
                     field_of_view = 45,
                     directions = NULL,
                     workers = NULL,
                     key = NULL,
                     quiet = FALSE) {
  if (inherits(x, 'NULL')) {
    if (!quiet) cli::cli_alert_info("Please input building footprint polygon generated by `search_3dglobdf()`.")
    return(x)
  }
  if (inherits(key, 'NULL')) {
    stop("API key for OpenTopography is missing.")
  }

  # Store the original 'timeout' option and ensure it's reset upon function exit
  original_timeout <- getOption('timeout')
  on.exit(options(timeout = original_timeout), add = TRUE)
  options(timeout=9999)

  old_opt <- getOption("future.globals.maxSize")
  on.exit(options(future.globals.maxSize = old_opt), add = TRUE)
  options(future.globals.maxSize = 3 * 1024^3)

  old_terra_progress <- terra::terraOptions(print = FALSE)$progress
  terra::terraOptions(progress = 0)
  on.exit(terra::terraOptions(progress = old_terra_progress), add = TRUE)

  normalize_source <- function(value, choices) {
    if (inherits(value, "NULL")) return(NULL)
    value <- tolower(as.character(value[1]))
    if (value %in% c("none", "null", "na")) return(NULL)
    match.arg(value, choices)
  }
  if (!inherits(datasource, "NULL")) {
    datasource <- normalize_source(datasource, c("metachm", "ethchm", "esri", "sentinel2"))
    if (datasource %in% c("metachm", "ethchm")) {
      datasource_canopy_height <- datasource
    } else {
      datasource_canopy_height <- NULL
      datasource_greenspace <- datasource
    }
  }
  datasource_canopy_height <- normalize_source(datasource_canopy_height, c("metachm", "ethchm"))
  datasource_greenspace <- normalize_source(datasource_greenspace, c("esri", "sentinel2"))
  if (inherits(datasource_canopy_height, "NULL") && inherits(datasource_greenspace, "NULL")) {
    stop("At least one of `datasource_canopy_height` or `datasource_greenspace` must be supplied.", call. = FALSE)
  }
  floor_step <- as.integer(floor_step[1])
  if (is.na(floor_step) || floor_step < 1L) floor_step <- 1L
  short_building_threshold <- as.numeric(short_building_threshold[1])
  if (is.na(short_building_threshold) || short_building_threshold <= 0) {
    stop("`short_building_threshold` must be a positive numeric value in meters.", call. = FALSE)
  }
  valid_directions <- c(
    "southwest", "southeast", "northeast", "northwest",
    "north", "east", "west", "south"
  )
  if (!inherits(directions, "NULL")) {
    directions <- unique(tolower(as.character(directions)))
    invalid_directions <- setdiff(directions, valid_directions)
    if (length(invalid_directions) > 0) {
      stop(
        sprintf(
          "`directions` contains invalid value(s): %s. Valid values are: %s.",
          paste(invalid_directions, collapse = ", "),
          paste(valid_directions, collapse = ", ")
        ),
        call. = FALSE
      )
    }
    field_of_view <- as.numeric(field_of_view[1])
    if (is.na(field_of_view) || field_of_view <= 0 || field_of_view > 360) {
      stop("`field_of_view` must be a numeric value greater than 0 and less than or equal to 360.", call. = FALSE)
    }
  } else {
    field_of_view <- NULL
  }

  if (inherits(workers, "NULL")) {
    workers <- min(max(1, as.numeric(future::availableCores()) - 1), 4)
  } else {
    workers <- as.integer(workers[1])
    if (is.na(workers) || workers < 1L) workers <- 1L
  }
  # Set future plan depending on OS
  os <- Sys.info()[["sysname"]]
  if (workers == 1) {
    future::plan(future::sequential)
  } else if (os == "Windows" || isFALSE(parallelly::supportsMulticore())) {
    future::plan(future::multisession, workers = workers)
  } else {
    future::plan(future::multicore, workers = workers)
  }
  on.exit(future::plan(future::sequential), add = TRUE)

  start_time <- Sys.time()

  input_bbox <- get_bbox(x)
  utm_crs <- get_utm_crs(input_bbox)
  projected_poly <- sf::st_transform(x, utm_crs)
  analysis_poly <- prepare_group_analysis_buildings(projected_poly)
  analysis_bbox <- get_bbox(sf::st_buffer(projected_poly, dist = radius))
  bbox_vector <- bbox_poly_to_list(analysis_bbox)

  # Download DEM, optional canopy height, and optional 2D greenspace.
  if (!quiet) cli::cli_alert_info('Start downloading BGVI raster inputs ...')
  dem <- get_dem(bbox_vector, key)
  chm_layers <- NULL
  if (!inherits(datasource_canopy_height, "NULL")) {
    chm_layers <- suppressMessages(get_chm(
      bbox_vector,
      min_tree_height,
      datasource = datasource_canopy_height
    ))
  }
  greenspace <- NULL
  if (!inherits(datasource_greenspace, "NULL")) {
    greenspace <- get_greenspace(
      bbox = analysis_bbox,
      buffer = NULL,
      type = datasource_greenspace,
      zoom = zoom,
      year = year,
      min_tree_height = min_tree_height
    )
  }

  analysis_poly$g_area <- as.numeric(sf::st_area(analysis_poly))

  if (isTRUE(floor)) {
    analysis_poly$estimated_floors <- round(analysis_poly$Height / 3)
    analysis_poly$estimated_floors <- base::ifelse(
      analysis_poly$g_area < 30 | analysis_poly$Height < short_building_threshold,
      1,
      analysis_poly$estimated_floors
    )
    analysis_poly$min_gvi <- 0
    analysis_poly$max_gvi <- 0
    analysis_poly$sd_gvi  <- 0
  }
  analysis_poly$mean_gvi <- 0
  analysis_poly$bottom_gvi <- 0
  analysis_poly$top_gvi <- 0

  # Build reusable, aligned AOI rasters once. Each target building then crops
  # these rasters locally and flattens only its own footprint.
  if (!inherits(chm_layers, "NULL")) {
    raster_res <- terra::res(chm_layers[[1]])[1]
  } else {
    dem_projected <- terra::project(dem, paste0("EPSG:", utm_crs), method = "near")
    raster_res <- terra::res(dem_projected)[1]
  }
  bh_all <- rasterize_height(projected_poly, analysis_bbox, raster_res)
  layers_to_align <- list(dem = dem, bh_all = bh_all)
  if (!inherits(chm_layers, "NULL")) {
    layers_to_align$chm <- chm_layers[[1]]
    layers_to_align$canopy_green <- chm_layers[[2]]
  }
  if (!inherits(greenspace, "NULL")) {
    layers_to_align$tile_green <- greenspace
  }
  aligned_layers <- do.call(unify_layers, c(list(analysis_bbox), layers_to_align))

  dem <- aligned_layers$dem
  bh_all <- aligned_layers$bh_all
  chm <- if (!is.null(aligned_layers$chm)) {
    aligned_layers$chm
  } else {
    terra::ifel(is.na(dem), NA, 0)
  }
  binary_green <- terra::ifel(is.na(dem), NA, 0)
  if (!is.null(aligned_layers$canopy_green)) {
    binary_green <- terra::ifel(aligned_layers$canopy_green == 1, 1, binary_green)
  }
  if (!is.null(aligned_layers$tile_green)) {
    binary_green <- terra::ifel(aligned_layers$tile_green == 1, 1, binary_green)
  }
  binary_green <- terra::ifel(binary_green == 1, 1, 0)

  # --- Parallel Processing ---
  # cli::cli_alert_info('Preparing parallel processing ...')
  if (!quiet) pb <- utils::txtProgressBar(min = 0, max = nrow(analysis_poly), style = 3)
  building_list <- lapply(seq_len(nrow(analysis_poly)), function(i) {
    if (!quiet) utils::setTxtProgressBar(pb, i)
    list(
      building = analysis_poly[i, ]
    )
  })
  if (!quiet) close(pb)

  # Save raster layers to disk to avoid pointer serialization issues
  dem_path <- tempfile(fileext = ".tif")
  chm_path <- tempfile(fileext = ".tif")
  binary_green_path <- tempfile(fileext = ".tif")
  bh_all_path <- tempfile(fileext = ".tif")
  terra::writeRaster(dem, dem_path, overwrite = TRUE)
  terra::writeRaster(chm, chm_path, overwrite = TRUE)
  terra::writeRaster(binary_green, binary_green_path, overwrite = TRUE)
  terra::writeRaster(bh_all, bh_all_path, overwrite = TRUE)
  on.exit(unlink(c(dem_path, chm_path, binary_green_path, bh_all_path)), add = TRUE)

  gvi_results <- furrr::future_map(
    building_list,
    function(b) compute_gvi_per_building(
      building = b$building,
      dem_path = dem_path,
      chm_path = chm_path,
      binary_green_path = binary_green_path,
      bh_all_path = bh_all_path,
      radius = radius,
      floor = floor,
      floor_step = floor_step,
      short_building_threshold = short_building_threshold,
      directions = directions,
      field_of_view = field_of_view
    ),
    .options = furrr::furrr_options(seed = TRUE),
    .progress = !quiet
  )

  analysis_poly$mean_gvi <- vapply(gvi_results, function(x) x$mean, numeric(1))
  analysis_poly$bottom_gvi <- vapply(gvi_results, function(x) x$bottom, numeric(1))
  analysis_poly$top_gvi <- vapply(gvi_results, function(x) x$top, numeric(1))
  if (isTRUE(floor)) {
    analysis_poly$min_gvi <- vapply(gvi_results, function(x) x$min, numeric(1))
    analysis_poly$max_gvi <- vapply(gvi_results, function(x) x$max, numeric(1))
    analysis_poly$sd_gvi  <- vapply(gvi_results, function(x) x$sd, numeric(1))
  }
  if (!inherits(directions, "NULL")) {
    for (direction in directions) {
      analysis_poly[[paste0("gvi_bottom_", direction)]] <- vapply(
        gvi_results,
        function(x) x$directions[[direction]]$bottom,
        numeric(1)
      )
      analysis_poly[[paste0("gvi_top_", direction)]] <- vapply(
        gvi_results,
        function(x) x$directions[[direction]]$top,
        numeric(1)
      )
      analysis_poly[[paste0("mean_gvi_", direction)]] <- vapply(
        gvi_results,
        function(x) x$directions[[direction]]$mean,
        numeric(1)
      )
      analysis_poly[[paste0("min_gvi_", direction)]] <- vapply(
        gvi_results,
        function(x) x$directions[[direction]]$min,
        numeric(1)
      )
      analysis_poly[[paste0("max_gvi_", direction)]] <- vapply(
        gvi_results,
        function(x) x$directions[[direction]]$max,
        numeric(1)
      )
      analysis_poly[[paste0("sd_gvi_", direction)]] <- vapply(
        gvi_results,
        function(x) x$directions[[direction]]$sd,
        numeric(1)
      )
    }
  }
  gvi_cols <- c("g_area", "mean_gvi", "bottom_gvi", "top_gvi")
  if (isTRUE(floor)) {
    gvi_cols <- c(gvi_cols, "estimated_floors", "min_gvi", "max_gvi", "sd_gvi")
  }
  if (!inherits(directions, "NULL")) {
    direction_cols <- unlist(lapply(directions, function(direction) {
      paste0(c("gvi_bottom_", "gvi_top_", "mean_gvi_", "min_gvi_", "max_gvi_", "sd_gvi_"), direction)
    }))
    gvi_cols <- c(gvi_cols, direction_cols)
  }
  projected_poly <- copy_group_results(projected_poly, analysis_poly, gvi_cols)
  # cli::cli_alert_success('Finished calculating GVIs')

  end_time <- Sys.time()
  process_time <- as.numeric(difftime(end_time, start_time, units = "secs"))
  if (!quiet) time_taken(process_time)

  return(projected_poly)
}

#' @description
#' `get_dng`: Calculate the distance to the nearest greenspace (DNG) patch
#' for each building volume
#' @param min_area numeric. (only required for `get_dng`) The minimum area
#' (the unit is defined by `unit`) of greenspace patches within the proximity of
#' a building.
#' For example, when `min_area = 500`, any greenspace patches with area less than
#' 500 square meter will be excluded.
#' @param unit character. (only required for `get_dng`) The unit for
#' `min_area`: 'm2','ha', and 'km2'.
#'
#' @return
#' `get_dng` returns an `sf` object identical to input \code{x},
#' with an additional column:
#' \code{dng}: Distance to nearest green space (tree canopy pixe)l (in meters).
#'
#' @examples
#' result <- gloBFPr::get_dng(#globfp_example[c(1:3),],
#'                            datasource = "metachm",
#'                            unit = "m2")
#' @export
#' @rdname get_metrics

get_dng <- function(x = NULL,
                     datasource = NULL,
                     min_tree_height = 2,
                     zoom = 17,
                     radius = 800,
                     min_area = 500,
                     unit = c('m2','ha','km2'),
                     year = NULL,
                     quiet = FALSE) {
  if (inherits(x, 'NULL')) {
    if (!quiet) cli::cli_alert_info("Please input building footprint polygon.")
    return(x)
  }

  unit <- match.arg(unit)
  if (inherits(datasource, 'NULL')) {
    stop("Please input datasource: 'metachm', 'esri', or 'sentinel2'.")
  }
  datasource <- match.arg(datasource, c("metachm", "esri", "sentinel2"))

  bbox <- get_bbox(x)
  utm_crs <- get_utm_crs(bbox)
  projected_poly <- sf::st_transform(x, utm_crs)
  analysis_poly <- prepare_group_analysis_buildings(projected_poly)
  analysis_poly$dng <- NA_real_

  for (i in seq_len(nrow(analysis_poly))) {
    poly_ <- analysis_poly[i, ]$geometry
    buffer_ <- get_buffer(x = poly_, radius = radius)
    gs <- get_greenspace(buffer_$bbox, buffer_$buffer, datasource, zoom, year, min_tree_height)
    gs <- filter_patch_area(gs, min_area, unit = unit, directions = 8)
    green_points <- terra::as.points(terra::ifel(gs == 1, 1, NA), na.rm = TRUE)
    if (nrow(green_points) == 0) next

    green_points_sf <- sf::st_as_sf(green_points)
    nearest_index <- sf::st_nearest_feature(buffer_$centroid, green_points_sf)
    nearest_point <- green_points_sf[nearest_index, ]
    distance <- sf::st_distance(buffer_$centroid, nearest_point)
    analysis_poly$dng[i] <- as.numeric(distance)
  }
  projected_poly <- copy_group_results(projected_poly, analysis_poly, "dng")
  return(projected_poly)
}

# get_neighbors <- function(x = NULL, radius = 500) {
#   if (missing(x)) {
#     stop("Please input building footprint polygon generated by `search_3dglobdf`")
#   }
#   projected_poly <- x
#   projected_poly$n_count <- 0
#   projected_poly$m_ndist <- NA
#   projected_poly$sd_ndist <- NA
#
#   start_time <- Sys.time()
#
#   for (i in seq_len(nrow(projected_poly))) {
#     poly_ <- projected_poly[i, ]
#
#     # Buffer around centroid
#     this_centroid <- suppressWarnings(sf::st_centroid(poly_))
#     buffer_zone <- sf::st_buffer(this_centroid, dist = radius)
#     buffer_zone <- sf::st_transform(buffer_zone, sf::st_crs(projected_poly))
#
#     # Filter by intersection with buffer
#     intersection_mat <- sf::st_intersects(projected_poly, buffer_zone, sparse = FALSE)[, 1]
#     if (sum(intersection_mat) <= 1) next  # only self or no neighbors
#
#     filtered_poly <- projected_poly[intersection_mat, ]
#     filtered_centroids <- sf::st_centroid(filtered_poly)
#
#     # Voronoi tessellation from filtered centroids
#     centroid_union <- sf::st_union(filtered_centroids)
#     voronoi_polygons <- sf::st_voronoi(centroid_union) |>
#       sf::st_collection_extract("POLYGON")
#     voronoi_sf <- sf::st_sf(geometry = sf::st_sfc(voronoi_polygons),
#                             crs = sf::st_crs(filtered_poly))
#     voronoi_sf$id <- seq_len(nrow(filtered_poly))
#
#     # Find index of current polygon in filtered_poly
#     index_in_filtered <- which(filtered_poly$id == poly_$id)
#     if (length(index_in_filtered) == 0) next
#
#     # Adjacency based on touching Voronoi cells
#     adjacency_matrix <- sf::st_touches(voronoi_sf)
#     neighbor_indices <- adjacency_matrix[[index_in_filtered]]
#
#     # Distance computation
#     if (length(neighbor_indices) > 0) {
#       neighbor_centroids <- filtered_centroids[neighbor_indices, ]
#       dists <- sf::st_distance(this_centroid, neighbor_centroids)
#       projected_poly$n_count[i] <- length(neighbor_indices)
#       projected_poly$m_ndist[i] <- mean(as.numeric(dists))
#       if (length(neighbor_indices) != 1) {
#         projected_poly$sd_ndist[i] <- sd(as.numeric(dists))
#       } else {
#         projected_poly$sd_ndist[i] <- NA
#       }
#     }
#   }
#   end_time <- Sys.time()
#   process_time <- as.numeric(difftime(end_time, start_time, units = "secs"))
#   if (process_time >= 60) {
#     cli::cli_alert_success(paste0("Completed. Time taken: ", base::round(process_time/60), " minutes."))
#   } else {
#     cli::cli_alert_success(paste0("Completed. Time taken: ", base::round(process_time), " seconds."))
#   }
#   return(projected_poly)
# }


# get_green_acc <- function(x = NULL,
#                           min_tree_height = 2,
#                           radius = 800,
#                           floor = FALSE,
#                           key = NULL,
#                           progress_bar = TRUE) {
#   if (inherits(x, 'NULL')) {
#     stop('Please input building footprint polygon generated by `search_3dglobdf`.')
#   }
#
#   if (inherits(key, 'NULL')) {
#     stop('API key of opentopography is missing.')
#   }
#
#   start_time <- Sys.time()
#   if(isTRUE(progress_bar)) {pb <- txtProgressBar(min=0, max = 100, style = 3)}
#
#   bbox <- get_bbox(x)
#   bbox_vector <- bbox_poly_to_list(bbox)
#   chm_layers <- suppressMessages(get_chm(bbox_vector, min_tree_height))
#   projected_poly <- x
#
#   # distance to the nearest green space (DNG) #
#   # convert tree raster into points
#   isolated_chm <- terra::ifel(chm_layers[[2]] == 0, NA, 1)
#   green_points <- terra::as.points(isolated_chm, na.rm = TRUE)
#   green_points_sf <- sf::st_as_sf(green_points)
#   building_centroids <- suppressWarnings(sf::st_centroid(x))
#   green_points_sf <- sf::st_transform(green_points_sf, crs = sf::st_crs(x))
#   # distance to the nearest green space pixel
#   nearest_index <- sf::st_nearest_feature(building_centroids, green_points_sf)
#   nearest_points <- green_points_sf[nearest_index, ]
#   distances <- sf::st_distance(building_centroids, nearest_points, by_element = TRUE)
#   projected_poly$dng <- as.numeric(distances)
#
#   # green view index (GVI) #
#   dem <- get_dem(bbox_vector, key)
#   # precompute DSM once (DEM + CHM)
#   chm_n_dem <- unify_layers(bbox, chm_layers[[1]], dem)
#   chm <- chm_n_dem[[1]]
#   binary_chm <- chm_layers[[2]]
#   dem <- chm_n_dem[[2]]
#   dsm <- chm + dem
#
#   projected_poly$g_area <- as.numeric(sf::st_area(projected_poly))
#
#   # estimate floor number if 'floor' is true
#   if (isTRUE(floor)) {
#     projected_poly$estimated_floors <- round(projected_poly$Height / 3)
#     projected_poly$estimated_floors <- base::ifelse(projected_poly$g_area < 30 || projected_poly$Height < 6,
#                                                     1,
#                                                     projected_poly$estimated_floors)
#     projected_poly$min_gvi <- 0
#     projected_poly$max_gvi <- 0
#     projected_poly$sd_gvi <- 0
#   }
#   projected_poly$mean_gvi <- 0
#
#   # loop
#   for (i in seq_len(nrow(projected_poly))) {
#     building <- projected_poly[i,]
#     p <- suppressWarnings(sf::st_centroid(building$geometry))
#     p <- as.vector(sf::st_coordinates(p))
#     p <- c(p[1], p[2])
#
#     bh <- rasterize_height(projected_poly[-c(i),], bbox, terra::res(dsm)[1])
#     chm_n_bh <- unify_layers(bbox, chm, bh)
#     bh <- chm_n_bh[[2]]
#     dsm_ <- bh + dsm
#
#     GVIs <- c()
#     if (isTRUE(floor)) {
#       for (h in 1:building$estimated_floors) {
#         height <- 1.7 + (h - 1) * 3
#         gvi <- get_gvi(dsm_, p, height, radius, building, binary_chm)
#         GVIs <- c(GVIs, gvi)
#       }
#       projected_poly$mean_gvi[i] <- mean(GVIs)
#       projected_poly$min_gvi[i] <- min(GVIs)
#       projected_poly$max_gvi[i] <- max(GVIs)
#       projected_poly$sd_gvi[i] <- if (length(GVIs) > 1) sd(GVIs) else NA
#     } else {
#       height_buttom <- 1.7
#       if (building$Height < 6) {
#         projected_poly$mean_gvi[i] <- get_gvi(dsm_, p, height_buttom, radius, building, binary_chm)
#       } else {
#         height_top <- 1.7 + building$Height - 3
#         gvi_top <- get_gvi(dsm_, p, height_top, radius, building, binary_chm)
#         gvi_buttom <- get_gvi(dsm_, p, height_buttom, radius, building, binary_chm)
#         projected_poly$mean_gvi[i] <- mean(c(gvi_top, gvi_buttom))
#       }
#     }
#   }
#
#   if(isTRUE(progress_bar)) {
#     setTxtProgressBar(pb, 100)
#     close(pb)
#   }
#
#   end_time <- Sys.time()
#   process_time <- as.numeric(difftime(end_time, start_time, units = "secs"))
#   if (process_time >= 60) {
#     cli::cli_alert_success(paste0("Completed. Time taken: ", base::round(process_time/60), " minutes."))
#   } else {
#     cli::cli_alert_success(paste0("Completed. Time taken: ", base::round(process_time), " seconds."))
#   }
#   return(projected_poly)
# }
