# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

mean_pairwise_distance <- function(coords) {
    .Call(`_gloBFPr_mean_pairwise_distance`, coords)
}

